# Generated by Django 5.1.1 on 2024-09-30 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallMe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30, verbose_name='Имя')),
                ('phone', models.CharField(max_length=30, verbose_name='Телефон')),
                ('email', models.CharField(max_length=30, verbose_name='E-mail')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Запрос звонка',
                'verbose_name_plural': 'Запросы звонков',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id_cat', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=60, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['category'],
                'indexes': [models.Index(fields=['category'], name='cars_catego_categor_c70d58_idx')],
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id_st', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=60, verbose_name='Новая/Уже нет')),
            ],
            options={
                'verbose_name': 'Новая/Уже нет',
                'verbose_name_plural': 'Новая/Уже нет',
                'ordering': ['status'],
                'indexes': [models.Index(fields=['status'], name='cars_status_status_9ae125_idx')],
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Название модели')),
                ('price', models.CharField(blank=True, max_length=250, null=True, verbose_name='Цена')),
                ('price_old', models.CharField(blank=True, max_length=250, null=True, verbose_name='Цена БЕЗ скидки')),
                ('year', models.CharField(blank=True, max_length=250, null=True, verbose_name='Год выпуска')),
                ('engine', models.CharField(blank=True, max_length=250, null=True, verbose_name='Двигатель, л/с')),
                ('mileage', models.CharField(blank=True, max_length=250, null=True, verbose_name='Пробег')),
                ('transmission', models.CharField(blank=True, max_length=250, null=True, verbose_name='Трансмиссия')),
                ('drive', models.CharField(blank=True, max_length=250, null=True, verbose_name='Привод')),
                ('main_img', models.ImageField(blank=True, null=True, upload_to='cars/', verbose_name='Фото главное')),
                ('img_1', models.ImageField(blank=True, null=True, upload_to='cars/', verbose_name='Фото 1')),
                ('img_2', models.ImageField(blank=True, null=True, upload_to='cars/', verbose_name='Фото 2')),
                ('img_3', models.ImageField(blank=True, null=True, upload_to='cars/', verbose_name='Фото 3')),
                ('img_4', models.ImageField(blank=True, null=True, upload_to='cars/', verbose_name='Фото 4')),
                ('img_5', models.ImageField(blank=True, null=True, upload_to='cars/', verbose_name='Фото 5')),
                ('img_6', models.ImageField(blank=True, null=True, upload_to='cars/', verbose_name='Фото 6')),
                ('img_7', models.ImageField(blank=True, null=True, upload_to='cars/', verbose_name='Фото 7')),
                ('available', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='cars.category', verbose_name='Категория')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='cars.status', verbose_name='Новая/Уже нет')),
            ],
            options={
                'verbose_name': 'Авто',
                'verbose_name_plural': 'Авто',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['id', 'name'], name='cars_car_id_53b6ad_idx')],
            },
        ),
    ]
