# Generated by Django 5.1.1 on 2024-10-03 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarSurvey_Full',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('car_characteristics', models.CharField(blank=True, max_length=300, null=True, verbose_name='Марка, модель, мотор')),
                ('country', models.CharField(blank=True, max_length=300, null=True, verbose_name='Из какой страны Вас интересует автомобиль?')),
                ('when', models.CharField(blank=True, max_length=300, null=True, verbose_name='Когда планируете покупать? ')),
                ('payment_type', models.CharField(blank=True, max_length=300, null=True, verbose_name='Форма оплаты за автомобиль? ')),
                ('max_price', models.CharField(blank=True, max_length=300, null=True, verbose_name='Максимальный бюджет для покупки?')),
                ('trade_in', models.CharField(blank=True, max_length=300, null=True, verbose_name='Планируете трейд ин? Какой авто? Пробег? ')),
                ('complectation', models.CharField(blank=True, max_length=600, null=True, verbose_name='Комплектация? ')),
                ('colors', models.CharField(blank=True, max_length=300, null=True, verbose_name='Желаемые цвета кузова и салона')),
                ('need_casco', models.CharField(blank=True, max_length=300, null=True, verbose_name='Планируете ли делать Каско')),
                ('real_price', models.CharField(blank=True, max_length=300, null=True, verbose_name='Какова стоимость реального предложения автомобиля, которое Вам удалось найти?')),
                ('first_name', models.CharField(max_length=30, verbose_name='Имя')),
                ('phone', models.CharField(max_length=30, verbose_name='Телефон')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Заказ машины: подробный опросник',
                'verbose_name_plural': 'Заказ машины: подробный опросник',
                'ordering': ['-created'],
            },
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ['status'], 'verbose_name': 'Новая / С пробегом', 'verbose_name_plural': 'Новая / С пробегом'},
        ),
        migrations.RemoveField(
            model_name='callme',
            name='email',
        ),
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(max_length=60, verbose_name='Новая / С пробегом'),
        ),
    ]
