# Generated by Django 5.1.1 on 2024-10-03 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_carsurvey_full_alter_status_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='img_10',
            field=models.ImageField(blank=True, null=True, upload_to='cars/', verbose_name='Фото 10'),
        ),
        migrations.AddField(
            model_name='car',
            name='img_8',
            field=models.ImageField(blank=True, null=True, upload_to='cars/', verbose_name='Фото 8'),
        ),
        migrations.AddField(
            model_name='car',
            name='img_9',
            field=models.ImageField(blank=True, null=True, upload_to='cars/', verbose_name='Фото 9'),
        ),
    ]
