# Generated by Django 5.1.1 on 2024-10-05 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_carsurveyfull_cascocount_guaranteecount_legalhelp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carsurveyfull',
            name='payment_type',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Форма оплаты за автомобиль?'),
        ),
        migrations.AlterField(
            model_name='carsurveyfull',
            name='trade_in',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Планируете трейд ин? Какой авто? Пробег?'),
        ),
    ]
