# Generated by Django 5.1.1 on 2024-10-07 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_alter_carsurveyfull_payment_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CallMe',
        ),
        migrations.DeleteModel(
            name='CarSurveyFull',
        ),
        migrations.DeleteModel(
            name='CascoCount',
        ),
        migrations.DeleteModel(
            name='GuaranteeCount',
        ),
        migrations.DeleteModel(
            name='LegalHelp',
        ),
        migrations.DeleteModel(
            name='NeedDiagnostic',
        ),
        migrations.DeleteModel(
            name='NeedServece',
        ),
        migrations.DeleteModel(
            name='ShesterenkyNeed',
        ),
        migrations.DeleteModel(
            name='WantThisCar',
        ),
    ]
