# Generated by Django 5.1.1 on 2024-10-22 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_callme_carsurveyfull_cascocount_guaranteecount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('color_id', models.AutoField(primary_key=True, serialize=False)),
                ('color_name', models.CharField(default='Бежевый', max_length=50, null=True, verbose_name='Название цвета')),
                ('color_code', models.CharField(default='#E5E1DF', max_length=50, null=True, verbose_name='Цвет в #HEX')),
            ],
            options={
                'verbose_name': 'Цвет HEX или RGBA',
                'verbose_name_plural': 'Цвета HEX или RGBA',
                'ordering': ['color_name'],
                'indexes': [models.Index(fields=['color_name'], name='cars_color_color_n_7dfa77_idx')],
            },
        ),
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='cars.color', verbose_name='Цвет'),
        ),
    ]
