# Generated by Django 5.1.1 on 2024-10-25 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_color_car_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.IntegerField(blank=True, max_length=25, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='car',
            name='price_old',
            field=models.IntegerField(blank=True, max_length=25, null=True, verbose_name='Цена БЕЗ скидки'),
        ),
    ]
