# Generated by Django 5.1.1 on 2024-10-31 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_alter_car_price_alter_car_price_old'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='drive',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Привод'),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Двигатель, л/с'),
        ),
        migrations.AlterField(
            model_name='car',
            name='mileage',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Пробег'),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Трансмиссия'),
        ),
    ]
