# Generated by Django 5.1.1 on 2024-11-11 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0011_alter_car_drive_alter_car_engine_alter_car_mileage_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CallMeItem',
        ),
    ]
