# Generated by Django 5.1.1 on 2024-12-16 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0013_alter_cascocount_budget_alter_legalhelp_documents_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id_brand', models.AutoField(primary_key=True, serialize=False)),
                ('brand', models.CharField(default='Audi', max_length=30, verbose_name='Марка')),
            ],
            options={
                'verbose_name': 'Марка',
                'verbose_name_plural': 'Марка',
                'ordering': ['brand'],
                'indexes': [models.Index(fields=['brand'], name='cars_brand_brand_eec161_idx')],
            },
        ),
        migrations.AddField(
            model_name='car',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='cars.brand', verbose_name='Марка'),
        ),
    ]
