# Generated by Django 5.1.1 on 2024-12-19 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0014_brand_car_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carsurveyfull',
            name='car_characteristics',
            field=models.TextField(blank=True, null=True, verbose_name='Марка, модель, мотор'),
        ),
        migrations.AlterField(
            model_name='carsurveyfull',
            name='colors',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Желаемые цвета кузова и салона'),
        ),
        migrations.AlterField(
            model_name='carsurveyfull',
            name='complectation',
            field=models.TextField(blank=True, max_length=600, null=True, verbose_name='Комплектация?'),
        ),
        migrations.AlterField(
            model_name='carsurveyfull',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Из какой страны Вас интересует автомобиль?'),
        ),
        migrations.AlterField(
            model_name='carsurveyfull',
            name='payment_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Форма оплаты за автомобиль?'),
        ),
        migrations.AlterField(
            model_name='carsurveyfull',
            name='real_price',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Какова стоимость реального предложения автомобиля, которое Вам удалось найти?'),
        ),
        migrations.AlterField(
            model_name='carsurveyfull',
            name='when',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Когда планируете покупать? '),
        ),
        migrations.AlterField(
            model_name='legalhelp',
            name='documents',
            field=models.TextField(blank=True, null=True, verbose_name='Какие документы у вас есть сейчас?'),
        ),
        migrations.AlterField(
            model_name='legalhelp',
            name='where_auto',
            field=models.TextField(blank=True, null=True, verbose_name='Где сейчас находится авто? В РФ/в др.стране/на таможне?'),
        ),
    ]
