# Generated by Django 5.1.1 on 2024-12-26 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0015_alter_carsurveyfull_car_characteristics_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callme',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Заявка поступила'),
        ),
        migrations.AlterField(
            model_name='carsurveyfull',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Заявка поступила'),
        ),
        migrations.AlterField(
            model_name='cascocount',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Заявка поступила'),
        ),
        migrations.AlterField(
            model_name='guaranteecount',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Заявка поступила'),
        ),
        migrations.AlterField(
            model_name='legalhelp',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Заявка поступила'),
        ),
        migrations.AlterField(
            model_name='needdiagnostic',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Заявка поступила'),
        ),
        migrations.AlterField(
            model_name='needdiagnostic',
            name='urgency',
            field=models.BooleanField(default=False, verbose_name='Срочно?'),
        ),
        migrations.AlterField(
            model_name='needservece',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Заявка поступила'),
        ),
        migrations.AlterField(
            model_name='needservece',
            name='urgency',
            field=models.BooleanField(default=False, verbose_name='Срочно?'),
        ),
        migrations.AlterField(
            model_name='shesterenkyneed',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Заявка поступила'),
        ),
        migrations.AlterField(
            model_name='wantthiscar',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Заявка поступила'),
        ),
    ]
