# Generated by Django 5.1.1 on 2024-12-26 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0016_alter_callme_created_alter_carsurveyfull_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wantthiscar',
            name='car_name',
            field=models.CharField(max_length=100, verbose_name='Марка машины'),
        ),
    ]
