# Generated by Django 5.1.1 on 2024-10-07 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_callme_carsurveyfull_cascocount_guaranteecount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wantthiscar',
            old_name='car_id',
            new_name='car_name',
        ),
        migrations.AlterField(
            model_name='carsurveyfull',
            name='need_casco',
            field=models.BooleanField(default=True, verbose_name='Планируете ли делать Каско?'),
        ),
    ]
